/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerscienceinternalassessment;



import static computerscienceinternalassessment.ColorThief.getPalette;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JTextField;


/**
 *
 * @author 14914
 */
public class MainGUIForCSIA extends javax.swing.JFrame {
    
    private ArrayList<Palette> paletteArray = new ArrayList<Palette>();

    /**
     * Creates new form MainGUIForProudIA
     */
    int r = 0;
    int g = 0;
    int b = 0;
    int count = 0;
    Color c = new Color(r, g, b);
    
    //palette from buffered image
    BufferedImage img;
    String filename;
    File file ; 
    
   
     


    public MainGUIForCSIA() {
        initComponents();
        myInit();
    }
    
    public void myInit(){
       
   
          jDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
               
            },
            new String [] {
                "Palette Name", "# Colors",  "For work?"
                    }));
        
          
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton11 = new javax.swing.JRadioButton();
        fileChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        displayColorTF = new javax.swing.JPanel();
        paletteNameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paletteDescriptionTA = new javax.swing.JTextArea();
        pickColorButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        redTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        greenTF = new javax.swing.JTextField();
        blueTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSwatchColor4 = new javax.swing.JTextField();
        addSwatchButton = new javax.swing.JButton();
        jTextFieldDisplayColor = new javax.swing.JTextField();
        ASwatchColor6 = new javax.swing.JTextField();
        ASwatchColor3 = new javax.swing.JTextField();
        ASwatchColor2 = new javax.swing.JTextField();
        showCurrentButton = new javax.swing.JButton();
        ASwatchColor1 = new javax.swing.JTextField();
        ASwatchColor9 = new javax.swing.JTextField();
        jButtonCreatePalette = new javax.swing.JButton();
        ASwatchColor5 = new javax.swing.JTextField();
        ASwatchColor10 = new javax.swing.JTextField();
        ASwatchColor8 = new javax.swing.JTextField();
        ASwatchColor7 = new javax.swing.JTextField();
        editedSelectedButton = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        forWorkCB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButtonAddImage = new javax.swing.JToggleButton();
        jButtonPaletteFromImage = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jButtonCreateFromImage = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jFrame11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDisplayTable = new javax.swing.JTable();
        jButtonRefreshTable = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CSwatchColor1 = new javax.swing.JTextField();
        CSwatchColor3 = new javax.swing.JTextField();
        CSwatchColor5 = new javax.swing.JTextField();
        CSwatchColor7 = new javax.swing.JTextField();
        CSwatchColor9 = new javax.swing.JTextField();
        CSwatchColor2 = new javax.swing.JTextField();
        CSwatchColor4 = new javax.swing.JTextField();
        CSwatchColor6 = new javax.swing.JTextField();
        CSwatchColor8 = new javax.swing.JTextField();
        CSwatchColor10 = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        buttonGroup1.add(jRadioButton11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Palette Name");

        jLabel2.setText("Palette Description");

        paletteDescriptionTA.setColumns(20);
        paletteDescriptionTA.setRows(5);
        jScrollPane1.setViewportView(paletteDescriptionTA);

        pickColorButton.setText("Add a color");
        pickColorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pickColorButtonMouseReleased(evt);
            }
        });

        jLabel6.setText("Manual Input");

        redTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTFActionPerformed(evt);
            }
        });

        jLabel3.setText("R");

        jLabel4.setText("G");

        jLabel5.setText("B");

        addSwatchButton.setText("Add swatch");
        addSwatchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addSwatchButtonMouseReleased(evt);
            }
        });

        jTextFieldDisplayColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisplayColorActionPerformed(evt);
            }
        });

        showCurrentButton.setText("Show current color");
        showCurrentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showCurrentButtonMouseReleased(evt);
            }
        });
        showCurrentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCurrentButtonActionPerformed(evt);
            }
        });

        ASwatchColor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASwatchColor9ActionPerformed(evt);
            }
        });

        jButtonCreatePalette.setText("Create palette");
        jButtonCreatePalette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonCreatePaletteMouseReleased(evt);
            }
        });

        editedSelectedButton.setText("Edit selected swatch");
        editedSelectedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editedSelectedButtonMouseReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton5);

        buttonGroup1.add(jRadioButton7);

        buttonGroup1.add(jRadioButton10);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);

        buttonGroup1.add(jRadioButton6);

        buttonGroup1.add(jRadioButton8);

        buttonGroup1.add(jRadioButton9);

        jLabel7.setText("For work");

        javax.swing.GroupLayout displayColorTFLayout = new javax.swing.GroupLayout(displayColorTF);
        displayColorTF.setLayout(displayColorTFLayout);
        displayColorTFLayout.setHorizontalGroup(
            displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayColorTFLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paletteNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forWorkCB))
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(redTF, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(greenTF)))))
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickColorButton)
                            .addComponent(jLabel6))))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayColorTFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCurrentButton)
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ASwatchColor3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ASwatchColor1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ASwatchColor5)
                            .addComponent(ASwatchColor7)
                            .addComponent(ASwatchColor9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreatePalette)
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ASwatchColor2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSwatchColor4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ASwatchColor6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ASwatchColor8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ASwatchColor10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(36, 36, 36)
                                .addComponent(editedSelectedButton))))
                    .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addSwatchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDisplayColor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        displayColorTFLayout.setVerticalGroup(
            displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayColorTFLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paletteNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(pickColorButton))
                .addGap(18, 18, 18)
                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel7))
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(greenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDisplayColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showCurrentButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSwatchButton)
                        .addGap(10, 10, 10)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(displayColorTFLayout.createSequentialGroup()
                                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(displayColorTFLayout.createSequentialGroup()
                                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(editedSelectedButton)
                                                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jRadioButton2)
                                                            .addComponent(jRadioButton1)))
                                                    .addComponent(ASwatchColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ASwatchColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton4)
                                                    .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jSwatchColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ASwatchColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jRadioButton3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ASwatchColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ASwatchColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jRadioButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ASwatchColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ASwatchColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton8)))
                            .addComponent(jRadioButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayColorTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ASwatchColor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ASwatchColor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreatePalette))
                    .addGroup(displayColorTFLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(forWorkCB)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manual Input", displayColorTF);

        jToggleButtonAddImage.setText("Select image");
        jToggleButtonAddImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButtonAddImageMouseReleased(evt);
            }
        });

        jButtonPaletteFromImage.setText("Build swatches from image");
        jButtonPaletteFromImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonPaletteFromImageMouseReleased(evt);
            }
        });

        jLabel9.setText("Palette Name");

        jLabel10.setText("Palette Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel11.setText("For work?");

        jButtonCreateFromImage.setText("Create Palette");
        jButtonCreateFromImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonCreateFromImageMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonAddImage)
                            .addComponent(jButtonPaletteFromImage)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jTextField12)
                                            .addComponent(jTextField10)
                                            .addComponent(jTextField8)
                                            .addComponent(jTextField6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField11)
                                            .addComponent(jTextField13)
                                            .addComponent(jTextField15)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCreateFromImage)
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jToggleButtonAddImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPaletteFromImage)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jButtonCreateFromImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create From Image", jPanel1);

        jDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Palette Name", "# Colors", "For work?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jDisplayTable);

        jButtonRefreshTable.setText("Refresh table");
        jButtonRefreshTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonRefreshTableMouseReleased(evt);
            }
        });
        jButtonRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshTableActionPerformed(evt);
            }
        });

        jButton5.setText("Display selected palette");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        jButton6.setText("Delete selected palette");

        CSwatchColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSwatchColor1ActionPerformed(evt);
            }
        });

        CSwatchColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSwatchColor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame11Layout = new javax.swing.GroupLayout(jFrame11);
        jFrame11.setLayout(jFrame11Layout);
        jFrame11Layout.setHorizontalGroup(
            jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame11Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRefreshTable)
                            .addComponent(jButton5)
                            .addGroup(jFrame11Layout.createSequentialGroup()
                                .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CSwatchColor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(CSwatchColor3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(26, 26, 26)
                                .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CSwatchColor2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSwatchColor10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(31, 31, 31))))
        );
        jFrame11Layout.setVerticalGroup(
            jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame11Layout.createSequentialGroup()
                        .addComponent(jButtonRefreshTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(27, 27, 27)
                        .addGroup(jFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame11Layout.createSequentialGroup()
                                .addComponent(CSwatchColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame11Layout.createSequentialGroup()
                                .addComponent(CSwatchColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSwatchColor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(140, 140, 140)
                        .addComponent(jButton6)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Display", jFrame11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void editedSelectedButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editedSelectedButtonMouseReleased
        if (jRadioButton1.isSelected()) {
            c = new Color(ASwatchColor1.getBackground().getRGB());
            showColorInTextField();
            count = 0;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton2.isSelected()) {
            c = new Color(ASwatchColor2.getBackground().getRGB());
            showColorInTextField();
            count = 1;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton3.isSelected()) {
            c = new Color(ASwatchColor3.getBackground().getRGB());
            showColorInTextField();
            count = 2;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton4.isSelected()) {
            c = new Color(jSwatchColor4.getBackground().getRGB());
            showColorInTextField();
            count = 3;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton5.isSelected()) {
            c = new Color(ASwatchColor5.getBackground().getRGB());
            showColorInTextField();
            count = 4;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton6.isSelected()) {
            c = new Color(ASwatchColor6.getBackground().getRGB());
            showColorInTextField();
            count = 5;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton7.isSelected()) {
            c = new Color(ASwatchColor7.getBackground().getRGB());
            showColorInTextField();
            count = 6;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton8.isSelected()) {
            c = new Color(ASwatchColor8.getBackground().getRGB());
            showColorInTextField();
            count = 7;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton9.isSelected()) {
            c = new Color(ASwatchColor9.getBackground().getRGB());
            showColorInTextField();
            count = 8;
            buttonGroup1.clearSelection();
            resetColor();
        } else if (jRadioButton10.isSelected()) {
            c = new Color(ASwatchColor10.getBackground().getRGB());
            showColorInTextField();
            count = 9;
            buttonGroup1.clearSelection();
            resetColor();
        }
    }//GEN-LAST:event_editedSelectedButtonMouseReleased

    private void jButtonCreatePaletteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreatePaletteMouseReleased
        // TODO add your handling code here:
// creates an array of colors
        int length = 0;
        Color swatchesArray[] = {ASwatchColor1.getBackground(), ASwatchColor2.getBackground(),
            ASwatchColor3.getBackground(), jSwatchColor4.getBackground(), ASwatchColor5.getBackground(),
            ASwatchColor6.getBackground(), ASwatchColor7.getBackground(), ASwatchColor8.getBackground(),
            ASwatchColor9.getBackground(), ASwatchColor10.getBackground()};

        Color test = new Color(swatchesArray[0].getRGB());
//determines length of palette               
        paletteDescriptionTA.setBackground(test);
        for (int i = 0; i < 10; i++) {
            Color c = new Color(swatchesArray[i].getRGB());
            if (c.equals(Color.WHITE)) {
                length = i;
                break;

            }
        }
             
        
        

        //adds palettes to array of palettes
        paletteArray.add(new Palette(paletteNameTF.getText(), paletteDescriptionTA.getText(),
        forWorkCB.getFocusTraversalKeysEnabled(), length, swatchesArray));
        
        paletteNameTF.setText("");
        paletteDescriptionTA.setText("");
        ASwatchColor1.setBackground(Color.WHITE);
        ASwatchColor2.setBackground(Color.WHITE);
        ASwatchColor3.setBackground(Color.WHITE);
        jSwatchColor4.setBackground(Color.WHITE);
        ASwatchColor5.setBackground(Color.WHITE);
        ASwatchColor6.setBackground(Color.WHITE);
        ASwatchColor7.setBackground(Color.WHITE);
        ASwatchColor8.setBackground(Color.WHITE);
        ASwatchColor9.setBackground(Color.WHITE);
        ASwatchColor10.setBackground(Color.WHITE);
        redTF.setText("");
        blueTF.setText("");
        greenTF.setText("");
        jTextFieldDisplayColor.setBackground(Color.WHITE);
        count = 0;
        


    }//GEN-LAST:event_jButtonCreatePaletteMouseReleased

    private void showCurrentButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCurrentButtonMouseReleased
        // TODO add your handling code here:
        r = Integer.parseInt(redTF.getText());
        g = Integer.parseInt(greenTF.getText());
        b = Integer.parseInt(blueTF.getText());
        //        Color temp = new Color(r,g,b);
        c = new Color(r, g, b);

        jTextFieldDisplayColor.setBackground(c);
    }//GEN-LAST:event_showCurrentButtonMouseReleased

    private void jTextFieldDisplayColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisplayColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisplayColorActionPerformed

    private void addSwatchButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSwatchButtonMouseReleased
        // TODO add your handling code here:
        //switch statements?
        switch (count) {
            case 0:
                ASwatchColor1.setBackground(c);
                count++;
                break;
            case 1:
                ASwatchColor2.setBackground(c);
                count++;
                break;
            case 2:
                ASwatchColor3.setBackground(c);
                count++;
                break;
            case 3:
                jSwatchColor4.setBackground(c);
                count++;
                break;
            case 4:
                ASwatchColor5.setBackground(c);
                count++;
                break;
            case 5:
                ASwatchColor6.setBackground(c);
                count++;
                break;
            case 6:
                ASwatchColor7.setBackground(c);
                count++;
                break;
            case 7:
                ASwatchColor8.setBackground(c);
                count++;
                break;
            case 8:
                ASwatchColor9.setBackground(c);
                count++;
                break;
            case 9:
                ASwatchColor10.setBackground(c);
                count++;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_addSwatchButtonMouseReleased

    private void redTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTFActionPerformed

    private void pickColorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickColorButtonMouseReleased
        // TODO add your handling code here:
        c = JColorChooser.showDialog(null, "Pick a color", Color.WHITE);
        jTextFieldDisplayColor.setBackground(c);
    }//GEN-LAST:event_pickColorButtonMouseReleased

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButtonRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshTableActionPerformed

    private void jButtonRefreshTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRefreshTableMouseReleased
        // TODO add your handling code here:
        SortAndSearchPalettes p = new SortAndSearchPalettes();
        p.selectionSortOfPalettes(paletteArray);
        
        
        if(paletteArray.size() <= jDisplayTable.getRowCount()){
            for(int row = 0; row < paletteArray.size(); row++){
                if(paletteArray.get(row).getForWork()){
                
                jDisplayTable.setValueAt(paletteArray.get(row).getPaletteName(), row, 0);
                jDisplayTable.setValueAt(paletteArray.get(row).getColorsQuantity(), row, 1);
                
                
                jDisplayTable.setValueAt("For work", row, 2);
                }
                else{
                    jDisplayTable.setValueAt("Personal", row, 2);
                    }
            }
            
            
           
        }
    }//GEN-LAST:event_jButtonRefreshTableMouseReleased

    private void CSwatchColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSwatchColor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSwatchColor1ActionPerformed

    private void jToggleButtonAddImageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonAddImageMouseReleased
        // TODO add your handling code here:
    
    

    if(evt.getSource()==jToggleButtonAddImage){
        fileChooser.showOpenDialog(null);
                    file = fileChooser.getSelectedFile();
                try {
                    
                        img=ImageIO.read(file);
                        Image resizedImage = img.getScaledInstance(jInternalFrame1.getWidth(), jInternalFrame1.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon icon=new ImageIcon(resizedImage); // ADDED
                        jLabel8.setIcon(icon); // ADDED

//                        Dimension imageSize = new Dimension(icon.getIconWidth(),icon.getIconHeight()); // ADDED
//                        jLabel8.setPreferredSize(imageSize); // ADDED
//
//                        jLabel8.revalidate(); // ADDED
//                        jLabel8.repaint(); // ADDED
                    }
                catch(IOException e1){}

    }
    if (evt.getSource()==jToggleButtonAddImage){
                    jInternalFrame1.setVisible(true);
                }
    
        
    }//GEN-LAST:event_jToggleButtonAddImageMouseReleased

    private void jButtonPaletteFromImageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPaletteFromImageMouseReleased
        // TODO add your handling code here:
       int [][] paletteArray = getPalette(img, 10);
       //PaletteArray p = new PaletteArray(getPalette(img, 10));
       Color [] colorsArray = new Color[10];
       for(int a = 0; a <10; a ++){
           Color c = new Color(paletteArray[a][0],paletteArray[a][1],paletteArray[a][2]);
           colorsArray[a] = c;
           if(a == 0){
               jTextField6.setBackground(c);
           }
           else if(a ==1){
               jTextField7.setBackground(c);
           }
           else if(a ==2){
               jTextField8.setBackground(c);
           }
           else if(a ==3){
               jTextField9.setBackground(c);
           }
           else if(a ==4){
               jTextField10.setBackground(c);
           }
           else if(a ==5){
               jTextField11.setBackground(c);
           }
           else if(a ==6){
               jTextField12.setBackground(c);
           }
           else if(a ==7){
               jTextField13.setBackground(c);
           }
           else if(a ==8){
               jTextField14.setBackground(c);
           }
           else if(a ==9){
               jTextField15.setBackground(c);
           }
       }
       
       
        
    }//GEN-LAST:event_jButtonPaletteFromImageMouseReleased

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButtonCreateFromImageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateFromImageMouseReleased
// creates an array of colors
        
        Color swatchesArray[] = {jTextField6.getBackground(), jTextField7.getBackground(),
            jTextField8.getBackground(), jTextField9.getBackground(), jTextField10.getBackground(),
            jTextField11.getBackground(), jTextField12.getBackground(), jTextField13.getBackground(),
           jTextField14.getBackground(), jTextField15.getBackground()};

      
        //adds palettes to array of palettes
        paletteArray.add(new Palette(jTextField16.getText(), jTextArea1.getText(),
       jCheckBox1.getFocusTraversalKeysEnabled(), 10, swatchesArray));
        
      
        jTextField16.setText("");
        jTextArea1.setText("");
        jTextField6.setBackground(Color.WHITE);
        jTextField7.setBackground(Color.WHITE);
        jTextField8.setBackground(Color.WHITE);
       jTextField9.setBackground(Color.WHITE);
        jTextField10.setBackground(Color.WHITE);
        jTextField11.setBackground(Color.WHITE);
        jTextField12.setBackground(Color.WHITE);
        jTextField13.setBackground(Color.WHITE);
        jTextField14.setBackground(Color.WHITE);
        jTextField15.setBackground(Color.WHITE);
      
                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateFromImageMouseReleased

    private void showCurrentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCurrentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCurrentButtonActionPerformed

    private void ASwatchColor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASwatchColor9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ASwatchColor9ActionPerformed

    private void CSwatchColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSwatchColor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSwatchColor2ActionPerformed

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        // TODO add your handling code here:
        int i = jDisplayTable.getSelectedRow();
        Color [] display = paletteArray.get(i).getColors();
        CSwatchColor1.setBackground(display[0]);
        CSwatchColor2.setBackground(display[1]);
        CSwatchColor3.setBackground(display[2]);
        CSwatchColor4.setBackground(display[3]);
        CSwatchColor5.setBackground(display[4]);
        CSwatchColor6.setBackground(display[5]);
        CSwatchColor7.setBackground(display[6]);
        CSwatchColor8.setBackground(display[7]);
        CSwatchColor9.setBackground(display[8]);
        CSwatchColor10.setBackground(display[9]);
        
    
    
        
    }//GEN-LAST:event_jButton5MouseReleased

    public void showColorInTextField() {

        jTextFieldDisplayColor.setBackground(c);
        redTF.setText(Integer.toString(c.getRed()));
        greenTF.setText(Integer.toString(c.getGreen()));
        blueTF.setText(Integer.toString(c.getBlue()));
    }

    public void resetColor() {
        r = 0;
        g = 0;
        b = 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIForCSIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIForCSIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIForCSIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIForCSIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIForCSIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ASwatchColor1;
    private javax.swing.JTextField ASwatchColor10;
    private javax.swing.JTextField ASwatchColor2;
    private javax.swing.JTextField ASwatchColor3;
    private javax.swing.JTextField ASwatchColor5;
    private javax.swing.JTextField ASwatchColor6;
    private javax.swing.JTextField ASwatchColor7;
    private javax.swing.JTextField ASwatchColor8;
    private javax.swing.JTextField ASwatchColor9;
    private javax.swing.JTextField CSwatchColor1;
    private javax.swing.JTextField CSwatchColor10;
    private javax.swing.JTextField CSwatchColor2;
    private javax.swing.JTextField CSwatchColor3;
    private javax.swing.JTextField CSwatchColor4;
    private javax.swing.JTextField CSwatchColor5;
    private javax.swing.JTextField CSwatchColor6;
    private javax.swing.JTextField CSwatchColor7;
    private javax.swing.JTextField CSwatchColor8;
    private javax.swing.JTextField CSwatchColor9;
    private javax.swing.JButton addSwatchButton;
    private javax.swing.JTextField blueTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel displayColorTF;
    private javax.swing.JButton editedSelectedButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JCheckBox forWorkCB;
    private javax.swing.JTextField greenTF;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCreateFromImage;
    private javax.swing.JButton jButtonCreatePalette;
    private javax.swing.JButton jButtonPaletteFromImage;
    private javax.swing.JButton jButtonRefreshTable;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTable jDisplayTable;
    private javax.swing.JPanel jFrame11;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSwatchColor4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldDisplayColor;
    private javax.swing.JToggleButton jToggleButtonAddImage;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea paletteDescriptionTA;
    private javax.swing.JTextField paletteNameTF;
    private javax.swing.JButton pickColorButton;
    private javax.swing.JTextField redTF;
    private javax.swing.JButton showCurrentButton;
    // End of variables declaration//GEN-END:variables
}
